# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d81bd2b335f31c2f11a14a87d152f026085fd2b6387695112d8704199e531e169f5df7d2ff5a4a9ab39411cc852679504fec138dbd6eceec12581051b8397a04
  sendgrid_username: <%= ENV["SECRET_SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SECRET_SENDGRID_PASSWORD"] %>


test:
  secret_key_base: 2b6400e5d12bdb0dffbe047f6fb0113a51d6347adc4d0a486af5af06f57cb835b7b528576cb56efe0b91d0fbb9136e5f825f20b3544b6a017fb33f2a9b699d89
  sendgrid_username: <%= ENV["SECRET_SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SECRET_SENDGRID_PASSWORD"] %>
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_username: <%= ENV["SECRET_SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SECRET_SENDGRID_PASSWORD"] %>
